### ISSUE TITLE
Using a extern database

### ISSUE THREAD

**Issue by duylong** [saez0pub/archlinux-jeedom#2]
Hi,

My database is not installed on localhost. I propose some modifications:
- Remove "mariadb" in depends or add in optionals ;
- Make dynamic the choice of database in "jeedom.postinstall.sh" ;

**Comment by saez0pub** [comment]
I've commited an update : https://github.com/saez0pub/archlinux-jeedom/commit/831666ce0e15ed502cb2055f68976979f819aaab and https://github.com/saez0pub/archlinux-jeedom/commit/c752362d3ba1810ceb9dd0377f511fddad713609
